### ISSUE TITLE
Enum type loses Enum Value

### ISSUE THREAD

**Issue by gxw8202** [BlackMATov/meta.hpp#108]
hi. I have a new questions:
     While the shared macro solves the problem of duplicate registration of enum type information, the evalue value is missing. How to solve this problem?

**Comment by BlackMATov** [comment]
Hello!

As I said earlier (in #107 issue), every DLL has its own type registry. Anything you bind in one library is only available to another if you pass the specific type through an exported function. In [this](https://github.com/BlackMATov/meta.hpp/blob/main/develop/unshared/meta_shared_exe/meta_shared_usage.cpp) example, I exported a function `shared::get_library_scope` that returns a scope from another library where I can find the enum I need.

Just remember that the types from different libraries are different, because they are in different registries. The macro `META_HPP_DEFINE_SHARED_TYPE` simply allows you to declare binary-compatible types for the runtime system, which can call functions with runtime arguments from another library as if they were created in the current one.

Little example how to get an enum type from another library:

```cpp
// DLL.hpp
YOUR_EXPORT_MACRO meta::scope get_library_scope();
```

```cpp
// DLL.cpp
enum class color { red, green, blue };

const auto libary_scope = []() -> meta::scope {
    meta::enum_<color>()
        .evalue_("red", color::red)
        .evalue_("green", color::green)
        .evalue_("blue", color::blue);
    return meta::local_scope_("library_scope")
        .typedef_<color>("color")
}();

meta::scope get_library_scope() {
    return library_scope;
}
```
```cpp
// EXE.cpp
#include "DLL.hpp"

const meta::enum_type color_type = get_library_scope().get_typedef("color").as_enum();
REQUIRE(color_type.get_evalues().size() == 3);
```

**Comment by BlackMATov** [comment]
Sometimes I think about making an optional possibility of a single shared registry of types. But this entails a bunch of other problems and difficulties, the list of which is too long to even write! But I will think about it again.

**Comment by gxw8202** [comment]
If the enum type is obtained from the method argument, the enum value of enum type will be lost.

**Comment by BlackMATov** [comment]
> If the enum type is obtained from the method argument, the enum value of enum type will be lost.

Can you show me a small example? I don't quite understand what exactly you mean.

**Comment by gxw8202** [comment]
I'll give an example tomorrow, it's a bit late today.

**Comment by gxw8202** [comment]
I handled the error of enum type at the application layer.This treatment is also elegant. I think a single shared registry of type is a good idea.
